server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventlyDB
    username: loco
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    timeout: 60000
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: none
  flyway:
    enabled: false
    user: loco
    password: pass
    schemas: eventlyDB
    url: jdbc:mysql://localhost:3306/eventlyDB
    locations: classpath:db/migration
  logging:
    level:
      org.hibernate.SQL: debug

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

amazonProperties:
  endpointUrl: https://s3.us-east-1.amazonaws.com
  accessKey: AKIAUNATVL73DEMNXPUY
  secretKey: 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
  bucketName: eventify-bucket