server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventlyDB
    username: loco
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    timeout: 60000
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: none
  flyway:
    enabled: true

  logging:
    level:
      org.hibernate.SQL: debug
