server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventlyDB
    username: loco
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create-update
        cache:
          use_second_level_cache: false
          use_query_cache: false
      show-sql: true
  logging:
    level:
      org.hibernate.SQL: debug
  security:
    oauht2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/eventos/protocol/openid-connect/token
        registration:
          keycloak:
            authorizationGrantType: client_credentials
            client-id: users-client
            client-secret: users-secret

dh:
  keycloak:
    serverUrl: http://localhost:8080/
    realm: eventos
    username: ${KEYCLOAK_USER:admin}
    password: ${KEYCLOAK_PASSWORD:admin}
    clientId: admin-cli